In [36]:
# Getting started with NumPy
# Sample
import numpy as np
a = [5, 10, 15, 20]
b = [[5, 10, 15], [20, 25, 30], [35, 40, 45]]
vector = np.array([5, 10, 15, 20])
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
#print(a)
#print(b)
print(vector)
print(matrix)


[ 5 10 15 20]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [37]:
# Sample 1
import numpy as np
vector = np.array([10, 20, 30])
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
print(vector)
print(matrix)

[10 20 30]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [38]:
vector = np.array([1, 2, 3, 4])
print(vector.shape)
matrix = np.array([[5, 10, 15], [20, 25, 30]])
print(matrix.shape)

(4,)
(2, 3)


In [39]:
import numpy as np
vector = np.array([10, 20, 30])
matrix = np.array([[5, 10, 15], [20, 25, 30]])
vector_shape = vector.shape
matrix_shape = matrix.shape
print(vector_shape)
print(type(vector_shape))
print(vector.dtype)
print(matrix_shape)

(3,)
<class 'tuple'>
int32
(2, 3)


In [63]:
import os
import numpy as np
os.chdir('C:\\Users\\S719789\\Desktop\\Data Science\\Dataquest\\Step 2\\Code_work')
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",")
print(type(world_alcohol))
world_alcohol_dtype = world_alcohol.dtype
print(world_alcohol_dtype)


<class 'numpy.ndarray'>
float64


In [64]:
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype="U75", skip_header=1)
print(world_alcohol) # first 3 and last 3 lines are displayed

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ..., 
 ['1986' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['1986' 'Africa' 'Swaziland' 'Other' '5.15']]


In [65]:
# Refresher on list accessing
vector = np.array([5, 10, 15, 20])
print(vector[0])
list_of_lists = [
        [5, 10, 15], 
        [20, 25, 30]
       ]
first_item= list_of_lists[0]
first_item1 = first_item[2]
print(first_item1)
print(list_of_lists[0][2])

5
15
15


In [66]:
uruguay_other_1986 = world_alcohol[1,4]
print(uruguay_other_1986)
third_country=world_alcohol[2,2]
print(third_country)

0.5
Cte d'Ivoire


In [67]:
matrix = np.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                 ])
print(matrix[:,1])
print(matrix[:,0:2])
print(matrix[1:3,:])
print(matrix[1:3,1])
print(matrix[1:3,0:2])


[10 25 40]
[[ 5 10]
 [20 25]
 [35 40]]
[[20 25 30]
 [35 40 45]]
[25 40]
[[20 25]
 [35 40]]


In [68]:
countries = world_alcohol[:,2]
alcohol_consumption = world_alcohol[:,4]
print(countries[:2])
print(alcohol_consumption[:2])
first_two_columns=world_alcohol[:,0:2]
first_ten_years =world_alcohol[0:10,0]
first_ten_rows =world_alcohol[0:10,:]
first_twenty_regions = world_alcohol[0:20,1:3]
print(first_two_columns)
print(first_ten_years)
print(first_ten_rows)
print(first_twenty_regions)

['Viet Nam' 'Uruguay']
['0' '0.5']
[['1986' 'Western Pacific']
 ['1986' 'Americas']
 ['1985' 'Africa']
 ..., 
 ['1986' 'Europe']
 ['1987' 'Western Pacific']
 ['1986' 'Africa']]
['1986' '1986' '1985' '1986' '1987' '1987' '1987' '1985' '1986' '1984']
[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ['1986' 'Americas' 'Colombia' 'Beer' '4.27']
 ['1987' 'Americas' 'Saint Kitts and Nevis' 'Beer' '1.98']
 ['1987' 'Americas' 'Guatemala' 'Other' '0']
 ['1987' 'Africa' 'Mauritius' 'Wine' '0.13']
 ['1985' 'Africa' 'Angola' 'Spirits' '0.39']
 ['1986' 'Americas' 'Antigua and Barbuda' 'Spirits' '1.55']
 ['1984' 'Africa' 'Nigeria' 'Other' '6.1']]
[['Western Pacific' 'Viet Nam']
 ['Americas' 'Uruguay']
 ['Africa' "Cte d'Ivoire"]
 ['Americas' 'Colombia']
 ['Americas' 'Saint Kitts and Nevis']
 ['Americas' 'Guatemala']
 ['Africa' 'Mauritius']
 ['Africa' 'Angola']
 ['Americas' 'Antigua and Barbuda']
 ['Africa' 

In [69]:
# Computation with NumPy
vector = np.array([5, 10, 15, 20])
print(vector == 10)
matrix = np.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                 ])
print(matrix == 25)

[False  True False False]
[[False False False]
 [False  True False]
 [False False False]]


In [70]:
years_1984 = (world_alcohol[:,0] == "1984")
countries_canada = (world_alcohol[:,2] == "Canada")
print(years_1984)
print(countries_canada)


[False False False ..., False False False]
[False False False ..., False False False]


In [71]:
vector = np.array([5, 10, 15, 20])
equal_to_ten = (vector == 10)
print(vector[equal_to_ten])
matrix = np.array([
                [5, 10, 15], 
                [20, 25, 30],
                [35, 40, 45]
             ])
second_column_25 = (matrix[:,1] == 25)
print(matrix[second_column_25, :])

[10]
[[20 25 30]]


In [72]:
country_is_algeria  = (world_alcohol[:,2] == "Algeria")
country_algeria = world_alcohol[country_is_algeria]
print(country_algeria)


[['1984' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Beer' '0.17']
 ['1987' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1986' 'Africa' 'Algeria' 'Wine' '0.1']
 ['1984' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Beer' '0.16']
 ['1989' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1989' 'Africa' 'Algeria' 'Wine' '0.23']
 ['1986' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1984' 'Africa' 'Algeria' 'Wine' '0.12']
 ['1985' 'Africa' 'Algeria' 'Beer' '0.19']
 ['1985' 'Africa' 'Algeria' 'Other' '0']
 ['1986' 'Africa' 'Algeria' 'Beer' '0.18']
 ['1985' 'Africa' 'Algeria' 'Wine' '0.11']
 ['1986' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Other' '0']
 ['1987' 'Africa' 'Algeria' 'Other' '0']
 ['1984' 'Africa' 'Algeria' 'Beer' '0.2']
 ['1985' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Wine' '0.1']]


In [73]:
vector = np.array([5, 10, 15, 20])
equal_to_ten_and_five = (vector == 10) & (vector == 5)
print(equal_to_ten_and_five)
equal_to_ten_or_five = (vector == 10) | (vector == 5)
print(equal_to_ten_or_five)

[False False False False]
[ True  True False False]


In [74]:
is_algeria_and_1986=(world_alcohol[:,0]=="1986") & (world_alcohol[:,2]=="Algeria")
rows_with_algeria_and_1986 = world_alcohol[is_algeria_and_1986,:]
print(rows_with_algeria_and_1986)

[['1986' 'Africa' 'Algeria' 'Wine' '0.1']
 ['1986' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1986' 'Africa' 'Algeria' 'Beer' '0.18']
 ['1986' 'Africa' 'Algeria' 'Other' '0']]


In [75]:
vector = np.array([5, 10, 15, 20])
equal_to_ten_or_five = (vector == 10) | (vector == 5)
vector[equal_to_ten_or_five] = 50
print(vector)
matrix = np.array([
            [5, 10, 15], 
            [20, 25, 30],
            [35, 40, 45]
         ])
second_column_25 = matrix[:,1] == 25
matrix[second_column_25, 1] = 10
print(matrix)

[50 50 15 20]
[[ 5 10 15]
 [20 10 30]
 [35 40 45]]


In [53]:
world_alcohol[:,0][world_alcohol[:,0] == '1986'] = '2014'
world_alcohol[:,3][world_alcohol[:,3] == 'Wine'] = 'Grog'



In [76]:
print([world_alcohol[:,0]])

[array(['1986', '1986', '1985', ..., '1986', '1987', '1986'], 
      dtype='<U75')]


In [77]:
print(world_alcohol[:,0][world_alcohol[:,0] == '1986'])

['1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986'
 '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986'
 '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986'
 '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986'
 '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986'
 '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986'
 '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986'
 '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986'
 '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986'
 '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986'
 '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986'
 '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986'
 '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986'
 '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986' '1986'
 '1986

In [78]:
is_value_empty=world_alcohol[:,4]==''
print(world_alcohol[is_value_empty])
world_alcohol[is_value_empty, 4] = '0'
print(world_alcohol[is_value_empty])

[['1985' 'Africa' 'Comoros' 'Other' '']
 ['1986' 'Europe' 'Italy' 'Other' '']
 ['1985' 'Europe' 'Lithuania' 'Other' '']
 ..., 
 ['1984' 'Europe' 'Czech Republic' 'Other' '']
 ['1987' 'Americas' 'Canada' 'Other' '']
 ['1986' 'Europe' 'Poland' 'Other' '']]
[['1985' 'Africa' 'Comoros' 'Other' '0']
 ['1986' 'Europe' 'Italy' 'Other' '0']
 ['1985' 'Europe' 'Lithuania' 'Other' '0']
 ..., 
 ['1984' 'Europe' 'Czech Republic' 'Other' '0']
 ['1987' 'Americas' 'Canada' 'Other' '0']
 ['1986' 'Europe' 'Poland' 'Other' '0']]


In [79]:
vector = np.array(["1", "2", "3"])
vector = vector.astype(float)
print(vector)

[ 1.  2.  3.]


In [80]:
alcohol_consumption = world_alcohol[:,4]
alcohol_consumption = alcohol_consumption.astype(float)
print(alcohol_consumption)
total_alcohol = alcohol_consumption.sum()
average_alcohol = alcohol_consumption.mean()
print(total_alcohol)
print(average_alcohol)

[ 0.    0.5   1.62 ...,  2.54  0.    5.15]
3908.96
1.20017193737


In [81]:
vector = np.array([5, 10, 15, 20])
print(vector.sum())
matrix = np.array([
                [5, 10, 15], 
                [20, 25, 30],
                [35, 40, 45]
             ])
print(matrix.sum(axis=1))
print(matrix.sum(axis=0))

50
[ 30  75 120]
[60 75 90]


In [85]:
canada_1986 =(world_alcohol[:,0]=="1986") & (world_alcohol[:,2]=="Canada")
canada_1986  = world_alcohol[canada_1986 ,:]
print(canada_1986)
canada_alcohol = canada_1986[:,4]
canada_alcohol = canada_alcohol.astype(float)
total_canadian_drinking = canada_alcohol.sum()
print(total_canadian_drinking)


[['1986' 'Americas' 'Canada' 'Other' '0']
 ['1986' 'Americas' 'Canada' 'Spirits' '3.11']
 ['1986' 'Americas' 'Canada' 'Beer' '4.87']
 ['1986' 'Americas' 'Canada' 'Wine' '1.33']]
9.31


In [92]:
countries = world_alcohol[:,2]
#print(countries)
totals = {}
is_year = world_alcohol[:,0] == "1989"
year = world_alcohol[is_year,:]
print(year)

for country in countries:
    is_country = year[:,2] == country
    country_consumption = year[is_country,:]
    alcohol_column = country_consumption[:,4]
    is_empty = alcohol_column == ''
    alcohol_column[is_empty] = "0"
    alcohol_column = alcohol_column.astype(float)
    totals[country] = alcohol_column.sum()
#print(totals)

highest_value = None
for i in totals:
    count=totals[i]
    if highest_value is None or count > highest_value:
        highest_value=count
print(highest_value)

highest_key=[]
for i in totals:
    if totals[i] == highest_value:
        highest_key.append(i)
print(highest_key)

highest_value = 0
highest_key = None
for country in totals:
    consumption = totals[country]
    if highest_value < consumption:
        highest_value = consumption
        highest_key = country

[['1989' 'Americas' 'Guatemala' 'Beer' '0.62']
 ['1989' 'Africa' 'Seychelles' 'Beer' '2.23']
 ['1989' 'Americas' 'Costa Rica' 'Spirits' '4.51']
 ..., 
 ['1989' 'Eastern Mediterranean' 'Morocco' 'Spirits' '0.07']
 ['1989' 'Europe' 'Poland' 'Beer' '2.03']
 ['1989' 'Europe' 'Turkey' 'Other' '0']]
16.29
['Hungary']


In [ ]:
# Another way of doing
highest_value = 0
highest_key = None
for country in totals:
    consumption = totals[country]
    if highest_value < consumption:
        highest_value = consumption
        highest_key = country